### ISSUE TITLE
Unable to connect to database, command wbconnect returns permission denied

### ISSUE THREAD

**Issue by ahalbert** [cosminadrianpopescu/vim-sql-workbench#16]
Version, Mac OS X
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 22 2016 08:48:25)

I'm trying to connect to a Redshift database I have with a working SQLWorkbench profile.
It runs wbconnect -profile CRS 

CRS is my profile.

It returns `executing job failed: permission denied`

My messages:
Error detected while processing function sw#server#handle_message[1]..<SNR>107_log_channel:
line    2:
E716: Key not present in Dictionary: channel 0 closed
E15: Invalid expression: s:channel_handlers[a:channel].log
line    3:
E121: Undefined variable: file
E116: Invalid arguments for function filereadable(file) ? 'ab' : 'wb'
E15: Invalid expression: filereadable(file) ? 'ab' : 'wb'
line    4:
E121: Undefined variable: file
E116: Invalid arguments for function writefile
Error detected while processing function sw#server#handle_message:

I enabled logging to files to try and solve the problem, but all I see is the wbconnect -profile CRS command. 

Any idea on how to resolve this issue?

**Comment by ahalbert** [comment]
Embarrsingly, I was looking at the permissions for the wrong sqlwbconsole.sh file, and and the one in my g:sw_exe did not have execute permissions. I'm commenting for anyone who has this problem.

**Comment by cosminadrianpopescu** [comment]
Thank you for the issue and for solving it.
