### ISSUE TITLE
Add an option to disable rename sql result tab using @wbresult

### ISSUE THREAD

**Issue by ricardoseriani** [cosminadrianpopescu/vim-sql-workbench#18]
Please, add an option to disable rename sql result tab using @wbresult, because certains databases not allow that kind of property

[https://groups.google.com/forum/#!topic/sql-workbench/mgnqE1XQvBo](https://groups.google.com/forum/#!topic/sql-workbench/mgnqE1XQvBo)

Old thread, but still I can't use it in some databases.

**Comment by cosminadrianpopescu** [comment]
Fixed with the pull request #19
