### ISSUE TITLE
Neovim missing "ch_setoptions" resulting in crash.

### ISSUE THREAD

**Issue by Chilinot** [cosminadrianpopescu/vim-sql-workbench#23]
It is not possible to use this plugin with Neovim, due to it lacking the "ch_setoptions" function available in regular Vim.

This function is referenced in three places in the source (at the moment of writing this). Is there a more "generic" alternative to handle callbacks in order to support Neovim?

**Comment by cosminadrianpopescu** [comment]
No, I thought that they implemented the vim way of handling channels. I will have a look and fix it these days. 

Thank you for noticing it.

**Comment by cosminadrianpopescu** [comment]
Fixed in the latest release. Now neovim should work again. Sorry about that.

**Comment by Chilinot** [comment]
Awesome thanks!
