### ISSUE TITLE
how to connect redshift from sqlwb Console.

### ISSUE THREAD

**Issue by ktmanoop** [cosminadrianpopescu/vim-sql-workbench#26]
How can i connect aws redshift from sql workbench console.

**Comment by cosminadrianpopescu** [comment]
You need to create a sql workbench profile in the GUI interface of sql workbench. See here: 
http://docs.aws.amazon.com/redshift/latest/mgmt/connecting-using-workbench.html

Once this is done, you can either use CtrlP and select the created profile or you can connect the vim buffer to sql workbench/j using SWSqlBufferConnect command and then, inside the sql file, execute the command wbconnect <profile>; (see the plugin documentation)
