### ISSUE TITLE
Can't connect unnamed buffer to a DB-Connection

### ISSUE THREAD

**Issue by borisbrodski** [cosminadrianpopescu/vim-sql-workbench#28]
Suppose you just copied a SQL-script from the browser into a clipboard and you want to run it within a brand new vim instance.

You do:

- `:enew`
- `"+p`
- `:CtrlP`, select your DB-profile and press enter

Should:
- You get a split windows with your SQL script above and the `__SQLResult__` below

Is:
- The unnamed buffer with your SQL has vanished (unsaved data is lost).
- No split window.
- The `__SQLResult__` buffer is fullscreen

Workaround:
- Save the unnamed buffer first

Info:
- Vim: 8.0
- vim-sql-workbench: 8.0.1

**Comment by borisbrodski** [comment]
I would like to add, that using this plugin for a while I find it really awesome!
Thank you very much!

**Comment by cosminadrianpopescu** [comment]
I will release a new version these days which includes the fixes for the #27. Mainly the problems that you noted with the space in the name of profiles and I also added the cache clearing for the CtrlP. 

Is true, that you cannot connect to a database an unnamed buffer (I never needed it for myself). I will try to fix this also, before releasing the 8.1 version.

**Comment by cosminadrianpopescu** [comment]
Please let me know if you find anything missing from `dbext`.

**Comment by cosminadrianpopescu** [comment]
Fixed in 8.1
