### ISSUE TITLE
Add a SWSqlSetDelimiter command

### ISSUE THREAD

**Issue by cosminadrianpopescu** [cosminadrianpopescu/vim-sql-workbench#32]
This command should change the delimiter for the given buffer. Useful for Oracle statements like 

```
BEGIN
    statement;
    ....
END;
/

**Comment by borisbrodski** [comment]
I don't think, it is sufficient. For example, I have often following mix in the buffer:

```
SELECT * FROM MY_TABLE;

BEGIN
  CALL_MY_METHOD();
END;
/

-- See results
SELECT * FROM RESULT;
```

In such a buffer I call one or another statement. The delimiter should be determined depending on the current statement and not on the entire buffer. Are you agree?

**Comment by cosminadrianpopescu** [comment]
That would be ideal and that is what `SQL Workbench/J` is doing in the GUI. However, with regular expressions (without a grammar lexer) this is quite difficult to implement. I don't want to add a grammar parser to the project, because this would mean adding again a dependency on python which I've eliminated in a previous version. 

Because if you are on the `BEGIN` when you type `<leader><c-space>`, then it's easy. But if you are in the middle of the statement, doing `<leader><c-space>` there the plugin will split by the `;` and execute it. It is very difficult (if not impossible) with regular expressions to realize that we are inside a `BEGIN - END` block. 

I propose to add another command, like `SWSqlExecuteCurrentWithAlternateDelimiter`, which would execute the current sql with an alternate delimiter (which can be set to `/`), without changing the current delimiter and then would proper split the file. 

What do you think?

**Comment by cosminadrianpopescu** [comment]
Fixed with the last commit. The `SWSqlExecuteSelected` and `SWSqlExecuteCurrent` commands now accept a `!` after them. If you use `SWSqlExecuteCurrent!`, then the alternate delimiter is used to split the sql (you can define the alternate delimiter in the connection properties).

This means that for your example buffer

```
SELECT * FROM MY_TABLE;

BEGIN
  CALL_MY_METHOD();
END;
/

-- See results
SELECT * FROM RESULT;
```

if you have the cursor between `BEGIN` and `END` and do `SWSqlExecuteCurrent!`, then the query sent to the server is still the same. This is because the alternate delimiter is used to split the sqls. So you have 2 solutions: either you select from `BEGIN` to `END` and use `SWSqlExecuteSelected!`, either you add an alternate delimiter before the `BEGIN` and you use the `SWSqlExecuteCurrent!`, like this:

```
SELECT * FROM MY_TABLE;
/
BEGIN
  CALL_MY_METHOD();
END;
/

-- See results
SELECT * FROM RESULT;
```

I hope this is clear. If not, please add a comment.
