### ISSUE TITLE
Add a command to execute the full file

### ISSUE THREAD

**Issue by cosminadrianpopescu** [cosminadrianpopescu/vim-sql-workbench#33]
Add a command which should execute the current file using a WbInclude current file.

**Comment by borisbrodski** [comment]
I would still prefer to automatically call this new command, if the block being executed exceeds some threshold. This will stop VIM from hanging in the regex.

**Comment by cosminadrianpopescu** [comment]
See #34 for this.

**Comment by borisbrodski** [comment]
Super! Thank you!

**Comment by cosminadrianpopescu** [comment]
SWInclude to include the current file. You can also do SWInclude <file> to include a given file. Another thing is that you can use !. Doing SWInclude! will use the alternate delimiter
