### ISSUE TITLE
Keep alternative buffer when switching to __SQLResult__ (already implemented?)

### ISSUE THREAD

**Issue by borisbrodski** [cosminadrianpopescu/vim-sql-workbench#36]
Please, keep altbuffer (Ctrl+6) when switching to `__SQLResult__`.

Since the `__SQLResult__` always a bottom split buffer, pressing Ctrl+6 in the upper split buffer (SQL or text) should not show the same  `__SQLResult__` no more time.

Consider following workflow:

- I have two SQL files: file1.sql and file2.sql, both connected to the database
- I switch multiple times between file1.sql and file2.sql in the upper split with Ctrl+6
- I run a query in file1.sql
- Then go to `__SQLResult__` with Ctrl+Wj to check the results
- Then go back to file1.sql with Ctrl+Wk
- Now, I would like to switch to file2.sql with Ctrl+6, but this brings `__SQLResult__` in the upper split.

I looks, like it could be done using `execute 'keepalt' a:cmd ...` (Credit: https://github.com/tpope/vim-vinegar/issues/25)

This would help a lot. Thank you!

**Comment by borisbrodski** [comment]
Sorry, just retested it, and it somehow works!!
Did you by chance implemented it in the last update?

**Comment by cosminadrianpopescu** [comment]
no, i haven't done anything yet. i will look into it.

**Comment by cosminadrianpopescu** [comment]
To be sure I've implemented the keepalt when switching to the results buffer automatically from code. Please note that if you switch to the results buffer with `<C-W>j`, then of course you will not have a keepalt.

**Comment by borisbrodski** [comment]
Thank you! How should I switch to the result buffer in order to preserve the alt-buffer?

**Comment by cosminadrianpopescu** [comment]
You have to make yourself a shortcut. 

When you execute a query, there is an automatic switch to the results buffer and back. This is where I've added the `keepalt`. But when you switch by yourself (`<C-W>j` is a standard `vim` shortcut), then you need to do the `keepalt` your self.
