### ISSUE TITLE
Always report g:sw_cache not set

### ISSUE THREAD

**Issue by Laputa-Yang** [cosminadrianpopescu/vim-sql-workbench#38]
I use the latest stable sql workbench version, and also the latest Vim version.
For me it always report that "There was a problem fetching the profiles for Sql Workbench (maybe the g:sw_cache) variable is not set? Please note that you need to either create the default folder (~/.cache/sw) either to set the variable to an existing folder for autocomplete or CtrlP integration to work"
I've checked the g:sw_cache is set to '~/.cache/sw'. This is auto set by your script, for me I just create the folder '~/.cache/sw'.
So don't understand why it still report this error? My vim is 8.1, sql workbench is Build124.

**Comment by cosminadrianpopescu** [comment]
Can you confirm that the folder exists (/home/<your-user>/.cache/sw, that the current user has read/write permissions to that folder and that the `g:sw_cache` variable point to that folder? 

The only explanation I have for this is that the user which you are using to start vim with does not have read / write permissions. 

Can you also provide information about your environment (which OS and either if it's gvim or vim or macvim that you are using?)

**Comment by ondrejlang** [comment]
I had the same problem, using console vim on linux, the problem was that there were no macros creted in SqlWorkbench/J (using build 124). With no macros defined, there was no WbMacros.xml file in the config folder. As soon as I created a dummy macro, there was no error in vim.
