### ISSUE TITLE
i can not connect database

### ISSUE THREAD

**Issue by met912** [cosminadrianpopescu/vim-sql-workbench#39]
I followed all the instructions but I can't make a connection.
Working on sqlwbconsole.sh but not working on vim

> OS
```
Ubuntu 18.04
```

> vim
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453
```

> vimrc
```
let g:ctrlp_extensions = ['sw_profiles']
let g:sw_exe = '/home/mete/Downloads/Workbench-Build124/sqlwbconsole.sh'
let g:sw_config_dir = '/home/mete/.sqlworkbench/'
let g:sw_cache = '~/.cache/sw' 

```

> Working on sqlwbconsole.sh

![its-work](https://user-images.githubusercontent.com/45111922/49681787-907f7a00-fab8-11e8-8eb3-f2c5650ee403.png)

> Not Working on vim

![not-work](https://user-images.githubusercontent.com/45111922/49681788-91181080-fab8-11e8-82ee-63339d66706d.png)

**Comment by cosminadrianpopescu** [comment]
Can you please attach the logs? Set the `g:sw_log_to_file` to true, and then, to see in which file the communication is logged, do `SWSqlShowLog`.

**Comment by met912** [comment]
i opened logs

> /tmp/-__SQL__-calisma

```
wbabout;exitwbconnect -profile="calisma";]0;SQL Workbench/J]0;SQL Workbench/JSQL Workbench/J (124) console interface started.
Enter exit to quit.
Enter WbHelp for a list of SQL Workbench/J specific commandsConfig directory: /home/mete/.sqlworkbench
SQL Workbench/J (124) console interface started.
Enter exit to quit.
Enter WbHelp for a list of SQL Workbench/J specific commands
Config directory: /home/mete/.sqlworkbench
SQL> wbabout;
]0;> SQL Workbench/JSQL> wbconnect -profile="calisma";]0;> SQL Workbench/J
Build 124 (2018-08-20 22:43)
Java Version: 10.0.2 (64bit)
Java Home: /usr/lib/jvm/java-11-openjdk-amd64
Settings file: /home/mete/.sqlworkbench/workbench.settings
Connection profiles: /home/mete/.sqlworkbench/WbProfiles.xml
Logfile: /home/mete/.sqlworkbench/workbench.log
Free Memory: 1958MB/1964MB
Execution time: 0.6s
]0;SQL Workbench/J
SQL> exit
A profile name or connection information is required.
Parameters for WbConnect are:
-profile        The name of the connection profile to connect to 
or
-username              The DB user for the connection
-password              The password for the DB user
-url                   The JDBC URL to connect to
-driver                The driver class to use
-driverJar             The classpath for the driver
-autocommit            Control the autocommit setting
-rollbackOnDisconnect  Issue a rollback before the connection is closed
-emptyStringIsNull     Treat empty strings as null
-trimCharData          Trim values from CHAR columns


Execution time: 0.85s
]0;SQL Workbench/J
SQL> 
```

**Comment by cosminadrianpopescu** [comment]
I see a strange character at the end of the Wbconnect. Can you try to set the `jline` to false? In the `workbench.settings`, you have to add the line `workbench.console.use.jline=false`. Please let me know if this fixes it. 

It's a very strange behavior. I've tried with the latest version (124.2) in cygwin and Linux and I don't have any issues.

**Comment by met912** [comment]
i still getting error :'(

![vim-error-sw](https://user-images.githubusercontent.com/45111922/49935651-a50da900-fee2-11e8-9b68-dc7557187a0b.png)

**Comment by cosminadrianpopescu** [comment]
I see this strange character at the end of the line `^[0d`, which means an escape and then a `0D`. Do you happen to use window line ending in your sql file in ubuntu? I really don't have an explanation and I didn't heard anybody having this issue. 

So, please make sure you are using unix line ending and `UTF-8` encoding for your sql file. Also, can you try to do from the command mode 

```
:SWSqlBufferConnect <path-to-your-sql-file>
:SWSqlExecuteNow wbconnect -profile="calisma"
:SWSqlExecuteNowLastResult
```
Please note that `SWSqlExecuteNow` will not output anything. If all this is ok, then I think it's a problem with your buffer.

**Comment by met912** [comment]
i recorded my screen

![vim 1](https://user-images.githubusercontent.com/45111922/50047333-0476df00-00c4-11e9-812e-bbcfe3ea2c0a.gif)

**Comment by cosminadrianpopescu** [comment]
I am thinking that maybe you have another vim plugin which is causing problems... Could you try on a vanila vim? Try backing up your `.vimrc`, and then just put in it the `sqlwb` options and include the `sqlwb` plugin.

I am really lost. I can see that your file is `UTF-8` and has `unix` line endings, so maybe is another plugin.

**Comment by met912** [comment]
i reconfigured my vimrc file. i moved all plugin folders ( excluding vim-sql-workbench)

> vimrc
```
set encoding=utf-8
setglobal fileencoding=utf-8

" SQL-WORKBENCK
let g:sw_exe = '/home/mete/Downloads/Workbench-Build124/sqlwbconsole.sh'
let g:sw_config_dir = '/home/mete/.sqlworkbench/'
let g:sw_cache = '~/.cache/sw'
let g:sw_log_to_file = 1
```

still the same error :'(

**Comment by met912** [comment]
a new error :). Do you use e-mail? Maybe you want to connect remotely

![image](https://user-images.githubusercontent.com/45111922/50059151-3788a380-0194-11e9-96db-39d70e304547.png)

**Comment by met912** [comment]
I think I'm editing the user's file workbench.settings: '(
Sorry it's my fault. 

```
"let g:sw_config_dir = '/home/mete/.sqlworkbench/' OLD 
let g:sw_config_dir = '/root/.sqlworkbench/'

let g:sw_cache = '~/.cache/sw'

```

it's work but this error why ? :'(

![image](https://user-images.githubusercontent.com/45111922/50059388-3016c980-0197-11e9-928a-06010f92dbad.png)

CtrlP profile error.

![image](https://user-images.githubusercontent.com/45111922/50059408-6eac8400-0197-11e9-88a4-b799d38bcbb2.png)

**Comment by cosminadrianpopescu** [comment]
> CtrlP profile error.

Does the folder `~/.cache/sw` exists? This folder has to exist.

**Comment by cosminadrianpopescu** [comment]
The errors that you have now are because the cache is not set properly. So am I to understand that the other problem has been solved?

**Comment by cosminadrianpopescu** [comment]
I use e-mail if you want me to look remotely, but you have to install and configure a VNC or something similar.

**Comment by met912** [comment]
i created cache file and solved the problem 😊😊

**Comment by cosminadrianpopescu** [comment]
So the original problem was caused by one of the already existing plugins?
